### ISSUE TITLE
Alt-r and Cmd+r do nothing in Mac OS

### ISSUE THREAD

**Issue by purefan** [bfrascher/Sublime-nRepeat#2]
installed it from the package control and tried Alt+r like the instructions say, but nothing happened. Tried with Cmd+r nothing happened. 
I currently cant find any combination to use this plugin

**Comment by bfrascher** [comment]
Hello purefan, thank you for your comment. Two quick questions to help isolate the problem:
Which version of Sublime Text are you using?
Have you tried rebinding the plugin command to a different key?

**Comment by bfrascher** [comment]
Closed as the problem could not be reproduced and no further information was provided.
